version: '3'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=news_recommend
    ports:
      - '5432:5432'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data 

  backend:
    build: ./backend
    image: backend
    container_name: backend
    network_mode: "host"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - key_words

  frontend:
    build: ./frontend
    image: frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  key-words:
    build: ./key_words
    image: key_words
    container_name: key_words
    ports:
      - "50052:50052"
