app_name = "news-api"

log_lelvel = "DEBUG"

[pgsql]
host = "localhost"
user = "postgres"
password = "001004"
dbname = "news"

[number]
max_news_num_of_page = 10
max_news_num_of_db = 300
increasement = 5